	;# 90 address transformations
	;# forced REX prefix is used to make all transformations 4 bytes long
	lea eax, [rax+rax*8+109]
	db 64
	xor eax, 96
	lea eax, [rax+rax*8-19]
	db 64
	add eax, -98
	db 64
	add eax, -21
	db 64
	xor eax, -80
	lea eax, [rax+rax*8-92]
	db 64
	add eax, 113
	lea eax, [rax+rax*8+100]
	db 64
	add eax, -39
	db 64
	xor eax, 120
	lea eax, [rax+rax*8-119]
	db 64
	add eax, -113
	db 64
	add eax, 111
	db 64
	xor eax, 104
	lea eax, [rax+rax*8-83]
	lea eax, [rax+rax*8+127]
	db 64
	xor eax, -112
	db 64
	add eax, 89
	db 64
	add eax, -32
	db 64
	add eax, 104
	db 64
	xor eax, -120
	db 64
	xor eax, 24
	lea eax, [rax+rax*8+9]
	db 64
	add eax, -31
	db 64
	xor eax, -16
	db 64
	add eax, 68
	lea eax, [rax+rax*8-110]
	db 64
	xor eax, 64
	db 64
	xor eax, -40
	db 64
	xor eax, -8
	db 64
	add eax, -10
	db 64
	xor eax, -32
	db 64
	add eax, 14
	lea eax, [rax+rax*8-46]
	db 64
	xor eax, -104
	lea eax, [rax+rax*8+36]
	db 64
	add eax, 100
	lea eax, [rax+rax*8-65]
	lea eax, [rax+rax*8+27]
	lea eax, [rax+rax*8+91]
	db 64
	add eax, -101
	db 64
	add eax, -94
	lea eax, [rax+rax*8-10]
	db 64
	xor eax, 80
	db 64
	add eax, -108
	db 64
	add eax, -58
	db 64
	xor eax, 48
	lea eax, [rax+rax*8+73]
	db 64
	xor eax, -48
	db 64
	xor eax, 32
	db 64
	xor eax, -96
	db 64
	add eax, 118
	db 64
	add eax, 91
	lea eax, [rax+rax*8+18]
	db 64
	add eax, -11
	lea eax, [rax+rax*8+63]
	db 64
	add eax, 114
	lea eax, [rax+rax*8+45]
	db 64
	add eax, -67
	db 64
	add eax, 53
	lea eax, [rax+rax*8-101]
	lea eax, [rax+rax*8-1]
	db 64
	xor eax, 16
	lea eax, [rax+rax*8-37]
	lea eax, [rax+rax*8-28]
	lea eax, [rax+rax*8-55]
	db 64
	xor eax, -88
	db 64
	xor eax, -72
	db 64
	add eax, 36
	db 64
	xor eax, -56
	db 64
	add eax, 116
	db 64
	xor eax, 88
	db 64
	xor eax, -128
	db 64
	add eax, 50
	db 64
	add eax, 105
	db 64
	add eax, -37
	db 64
	xor eax, 112
	db 64
	xor eax, 8
	db 64
	xor eax, -24
	lea eax, [rax+rax*8+118]
	db 64
	xor eax, 72
	db 64
	xor eax, -64
	db 64
	add eax, 40
	lea eax, [rax+rax*8-74]
	lea eax, [rax+rax*8+82]
	lea eax, [rax+rax*8+54]
	db 64
	xor eax, 56
	db 64
	xor eax, 40
	db 64
	add eax, 87