	;# 90 address transformations
	;# forced REX prefix is used to make all transformations 4 bytes long
	lea ecx, [rcx+rcx*8+109]
	db 64
	xor ecx, 96
	lea ecx, [rcx+rcx*8-19]
	db 64
	add ecx, -98
	db 64
	add ecx, -21
	db 64
	xor ecx, -80
	lea ecx, [rcx+rcx*8-92]
	db 64
	add ecx, 113
	lea ecx, [rcx+rcx*8+100]
	db 64
	add ecx, -39
	db 64
	xor ecx, 120
	lea ecx, [rcx+rcx*8-119]
	db 64
	add ecx, -113
	db 64
	add ecx, 111
	db 64
	xor ecx, 104
	lea ecx, [rcx+rcx*8-83]
	lea ecx, [rcx+rcx*8+127]
	db 64
	xor ecx, -112
	db 64
	add ecx, 89
	db 64
	add ecx, -32
	db 64
	add ecx, 104
	db 64
	xor ecx, -120
	db 64
	xor ecx, 24
	lea ecx, [rcx+rcx*8+9]
	db 64
	add ecx, -31
	db 64
	xor ecx, -16
	db 64
	add ecx, 68
	lea ecx, [rcx+rcx*8-110]
	db 64
	xor ecx, 64
	db 64
	xor ecx, -40
	db 64
	xor ecx, -8
	db 64
	add ecx, -10
	db 64
	xor ecx, -32
	db 64
	add ecx, 14
	lea ecx, [rcx+rcx*8-46]
	db 64
	xor ecx, -104
	lea ecx, [rcx+rcx*8+36]
	db 64
	add ecx, 100
	lea ecx, [rcx+rcx*8-65]
	lea ecx, [rcx+rcx*8+27]
	lea ecx, [rcx+rcx*8+91]
	db 64
	add ecx, -101
	db 64
	add ecx, -94
	lea ecx, [rcx+rcx*8-10]
	db 64
	xor ecx, 80
	db 64
	add ecx, -108
	db 64
	add ecx, -58
	db 64
	xor ecx, 48
	lea ecx, [rcx+rcx*8+73]
	db 64
	xor ecx, -48
	db 64
	xor ecx, 32
	db 64
	xor ecx, -96
	db 64
	add ecx, 118
	db 64
	add ecx, 91
	lea ecx, [rcx+rcx*8+18]
	db 64
	add ecx, -11
	lea ecx, [rcx+rcx*8+63]
	db 64
	add ecx, 114
	lea ecx, [rcx+rcx*8+45]
	db 64
	add ecx, -67
	db 64
	add ecx, 53
	lea ecx, [rcx+rcx*8-101]
	lea ecx, [rcx+rcx*8-1]
	db 64
	xor ecx, 16
	lea ecx, [rcx+rcx*8-37]
	lea ecx, [rcx+rcx*8-28]
	lea ecx, [rcx+rcx*8-55]
	db 64
	xor ecx, -88
	db 64
	xor ecx, -72
	db 64
	add ecx, 36
	db 64
	xor ecx, -56
	db 64
	add ecx, 116
	db 64
	xor ecx, 88
	db 64
	xor ecx, -128
	db 64
	add ecx, 50
	db 64
	add ecx, 105
	db 64
	add ecx, -37
	db 64
	xor ecx, 112
	db 64
	xor ecx, 8
	db 64
	xor ecx, -24
	lea ecx, [rcx+rcx*8+118]
	db 64
	xor ecx, 72
	db 64
	xor ecx, -64
	db 64
	add ecx, 40
	lea ecx, [rcx+rcx*8-74]
	lea ecx, [rcx+rcx*8+82]
	lea ecx, [rcx+rcx*8+54]
	db 64
	xor ecx, 56
	db 64
	xor ecx, 40
	db 64
	add ecx, 87