	mov rax, 1613783669344650115
	add rax, rcx
	mul rax
	sub rax, rdx ;# 1
	mul rax
	sub rax, rdx ;# 2
	mul rax
	sub rax, rdx ;# 3
	mul rax
	sub rax, rdx ;# 4
	mul rax
	sub rax, rdx ;# 5
	mul rax
	sub rax, rdx ;# 6
	mul rax
	sub rax, rdx ;# 7
	mul rax
	sub rax, rdx ;# 8
	mul rax
	sub rax, rdx ;# 9
	mul rax
	sub rax, rdx ;# 10
	mul rax
	sub rax, rdx ;# 11
	mul rax
	sub rax, rdx ;# 12
	mul rax
	sub rax, rdx ;# 13
	mul rax
	sub rax, rdx ;# 14
	mul rax
	sub rax, rdx ;# 15
	mul rax
	sub rax, rdx ;# 16
	mul rax
	sub rax, rdx ;# 17
	mul rax
	sub rax, rdx ;# 18
	mul rax
	sub rax, rdx ;# 19
	mul rax
	sub rax, rdx ;# 20
	mul rax
	sub rax, rdx ;# 21
	mul rax
	sub rax, rdx ;# 22
	mul rax
	sub rax, rdx ;# 23
	mul rax
	sub rax, rdx ;# 24
	mul rax
	sub rax, rdx ;# 25
	mul rax
	sub rax, rdx ;# 26
	mul rax
	sub rax, rdx ;# 27
	mul rax
	sub rax, rdx ;# 28
	mul rax
	sub rax, rdx ;# 29
	mul rax
	sub rax, rdx ;# 30
	mul rax
	sub rax, rdx ;# 31
	mul rax
	sub rax, rdx ;# 32
	mul rax
	sub rax, rdx ;# 33
	mul rax
	sub rax, rdx ;# 34
	mul rax
	sub rax, rdx ;# 35
	mul rax
	sub rax, rdx ;# 36
	mul rax
	sub rax, rdx ;# 37
	mul rax
	sub rax, rdx ;# 38
	mul rax
	sub rax, rdx ;# 39
	mul rax
	sub rax, rdx ;# 40
	mul rax
	sub rax, rdx ;# 41
	mul rax
	sub rax, rdx ;# 42
	ret